version: '3'
services:
  nodejs:
    image: node_consulta_credito
    restart: always
    build: .
    ports:
      - 8080
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - ./db_consulta_credito:/var/lib/postgresql/data
    ports:
      - 49153
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=consulta_credito